### PR TITLE
Fixed ability to add weird dates

### LINKED ISSUE #80: Exception handling for silly start/end dates
# You can add items with:
## a `start` datetime that is after the `end` datetime which doesn't make sense

This affects `add` and `edit`.

For `add`:

``` bash
# this command works
add "walk dog" from tomorrow 5pm to today 6pm
```

For `edit`:

``` bash
# suppose the following item already inside taskbook:

####################################
#1. Walk Lion
# Today, 5:00PM - 6:00PM
#2 hours from now
####################################

# this command works
edit 1 start:tomorrow 6pm

# yields the resulting item
####################################
#1. Walk Lion
# Tomorrow, 6:00PM - Today, 6:00PM
#21 hours from now
####################################
```
## datetimes that are several centuries away which is not within a human timeframe

The oldest human who has ever lived was just under 123 years old.

``` bash
# this also works
add "write CFG essay" by 11 november 2317 6pm

# yields the resulting item
####################################
#1. Walk Lion
# Sun 11 Nov 2317, 6:00PM
#3 centuries from now
####################################
```

I am not sure if we should fix the second one or leave it as an outlet for a user's free expression of their productivity.

### LINKED ISSUE #99: Edit doesn't fail on bad description detail
Descriptions can only be made of alphanumeric characters and spaces. The `edit` command does not give appropriate feedback when the description is modified to something invalid characters like an exclamation mark.

Suppose the following Item is in the taskbook:
```
1. Walk Dog
Today, 5PM - 6PM
2 hours from now
```

`edit 1 desc:walk lion!` does not do anything (as expected) but the UI returns a successful message (the green box)

### PR DESCRIPTION
**Pull request by craaaa**
Fixes #80, incidentally fixes #99 
Prevents adding and editing an event to give it a `startDate` that is after its `endDate`, or an `endDate` that is after its `startDate`

### CODE REVIEW

File: src/main/java/seedu/sudowudo/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -87,31 +87,35 @@ public CommandResult execute() {
...
-                    DateTimeParser parser = new DateTimeParser(editField[1]);
-                    model.setItemStart(itemToModify, parser.extractStartDate());
-                    model.setItemEnd(itemToModify, parser.extractEndDate());
-                    break;
-                default:
-                    // field names not valid
-                    return new CommandResult(MESSAGE_INVALID_FIELD);
+            try {
+                switch (editField[0]) {
+                    case "desc":
```
Comment (darrenwee) [inline src/main/java/seedu/sudowudo/logic/commands/EditCommand.java:92]: Code standard violation. `case` statement should be flush to `switch`.

Should look like:

``` java
switch(editField[0]) {
case "desc":
case "description":
    // statements blah blah
    break;
case "start":
    // statements blah blah blah
    break;
// ...
```

I fixed this in #104 though so just leave it

File: src/main/java/seedu/sudowudo/model/item/Item.java [hunk 2]
```diff
@@ -57,200 +53,197 @@ public Item(Description desc, UniqueTagList tags) {
...
-		notifyObservers();
+        setChanged();
+        notifyObservers();
     }
 
-    
     @Override
-	public void setIsDone(boolean doneness) {
+    public void setIsDone(boolean doneness) {
         this.isDone = doneness;
```
Comment (darrenwee) [inline src/main/java/seedu/sudowudo/model/item/Item.java]: Change parameter `doneness` to `isDone` (it's my fault originally I'm sorry 😭 ) for coding standard

File: src/main/java/seedu/sudowudo/model/item/Item.java [hunk 3]
```diff
@@ -57,200 +53,197 @@ public Item(Description desc, UniqueTagList tags) {
...
+        setChanged();
+        notifyObservers();
     }
 
-    public void setRecurring(boolean isRecurring) {
-        this.isRecurring = isRecurring;
-		setChanged();
-		notifyObservers();
+    private boolean isValidInterval(LocalDateTime start, LocalDateTime end) {
+        return start == null || end == null || start.isBefore(end);
```
Comment (darrenwee) [inline src/main/java/seedu/sudowudo/model/item/Item.java:254]: Doesn't handle `Item`s with null `startDate` or `endDate` properly. A task has a null `startDate`. A floating task has null `startDate` and `endDate`.

File: src/main/java/seedu/sudowudo/model/item/Item.java [hunk 4]
```diff
@@ -263,42 +256,45 @@ public String toString() {
...
-        otherStart = assignDummyLDT(other.getStartDate());
-        otherEnd = assignDummyLDT(other.getEndDate());
+        LocalDateTime thisStart = assignDummyLDT(this.startDate);
+        LocalDateTime thisEnd = assignDummyLDT(this.endDate);
+        LocalDateTime otherStart = assignDummyLDT(other.getStartDate());
+        LocalDateTime otherEnd = assignDummyLDT(other.getEndDate());
         
-        if(thisStart.isBefore(otherStart)) {
+        // Assign same start/end date to a deadline for easier checking
+        if (this.is(Type.TASK.toString())){
```
Comment (darrenwee) [inline src/main/java/seedu/sudowudo/model/item/Item.java]: Override the `toString` method in the enum `Type` (inside `Item.java`) so that it is not necessary to call `toString()` here for cleanliness' sake.

Change should be:

``` java
public enum Type {
        // blah blah some important stuff here

        /* let's get rid of this method
        public String getTypeName() {
            return this.typeName;
        }
        */

        // and put this one in its place
        @Override
        public String toString() {
            return this.typeName;
        }
    }
```

The new condition in this line would be

``` java
if (this.is(Type.TASK)) {
```

File: src/main/java/seedu/sudowudo/model/item/Item.java [hunk 5]
```diff
@@ -263,42 +256,45 @@ public String toString() {
...
+            thisStart = thisEnd;
+        }
+        if (other.is(Type.TASK.toString())){
+            otherStart = otherEnd;
+        }
+
+        if(thisEnd.isBefore(otherEnd)) {
+        // this item ends earlier
+            return -1;
+        } else if(thisEnd.isAfter(otherEnd)){
```
Comment (darrenwee) [inline src/main/java/seedu/sudowudo/model/item/Item.java]: Coding standard. Add whitespace before brace (just run the auto-formatter on the entire class).

File: src/test/java/seedu/sudowudo/logic/LogicManagerTest.java [hunk 6]
```diff
@@ -722,6 +723,50 @@ public void execute_editIndexNotFound_errorMessageShown() throws Exception {
...
+        TestDataHelper helper = new TestDataHelper();
+        Item initial = helper.workingItemWithDates("valid", LocalDateTime.of(2016, 10, 10, 10, 10, 10),
+                                                            LocalDateTime.of(2016, 11, 11, 11, 11, 11));
+        Item target = helper.workingItemWithDates("valid", LocalDateTime.of(2015, 10, 10, 10, 10, 10),
+                                                            LocalDateTime.of(2015, 11, 11, 11, 11, 11));
+        List<Item> initialList = helper.generateItemList(initial);
+        List<Item> targetList = helper.generateItemList(target);
+        helper.addToModel(model, initialList);
+        TaskBook expectedTB = helper.generateTaskBook(targetList);
+        assertCommandBehavior("edit 1 period: 2015 10 10 10 10:10 to 2015 11 11 11 11:11",
```
Comment (darrenwee) [inline src/test/java/seedu/sudowudo/logic/LogicManagerTest.java]: Why is this supposed to be a successful command? Natty can't handle this date token.

File: src/test/java/seedu/sudowudo/logic/LogicManagerTest.java [hunk 7]
```diff
@@ -794,7 +839,8 @@ private Item workingItemWithTags(String... tagged) throws Exception {
         //@@author A0131560U
         private Item workingItemWithDates(String desc, LocalDateTime... times) throws Exception {
             Description description = new Description(desc);
-            LocalDateTime startDate = null, endDate = null;
+            LocalDateTime startDate = null,
+                          endDate = null;
```
Comment (darrenwee) [inline src/test/java/seedu/sudowudo/logic/LogicManagerTest.java]: CODING STANDARD VIOLATION 🚔 

``` java
LocalDateTime startDate = null;
LocalDateTime endDate = null;
```

File: src/test/java/seedu/sudowudo/testutil/ItemBuilder.java [hunk 8]
```diff
@@ -25,7 +25,11 @@ public ItemBuilder withDates(String startdate) throws IllegalValueException{
     	DateTimeParser parser = new DateTimeParser(startdate);
 		LocalDateTime startTimeObj = parser.extractStartDate();
 		LocalDateTime endTimeObj = parser.extractStartDate();
-		this.item.setStartDate(startTimeObj);
+
+		// if the item is an event
+		if (startTimeObj != null && !startTimeObj.equals(endTimeObj)){
+		    this.item.setStartDate(startTimeObj);
```
Comment (darrenwee) [inline src/test/java/seedu/sudowudo/testutil/ItemBuilder.java:32]: Violate SLAP 🚔 

Refactor to `Item.is(Type.EVENT)`

File: src/test/java/seedu/sudowudo/testutil/ItemBuilder.java [hunk 9]
```diff
@@ -25,7 +25,11 @@ public ItemBuilder withDates(String startdate) throws IllegalValueException{
     	DateTimeParser parser = new DateTimeParser(startdate);
 		LocalDateTime startTimeObj = parser.extractStartDate();
```
Comment (darrenwee) [inline src/test/java/seedu/sudowudo/testutil/ItemBuilder.java:27]: Some funky indentation going on? CODE STANDARD VIOLATION 🚔

File: src/test/java/seedu/sudowudo/testutil/TestItem.java [hunk 10]
```diff
@@ -117,7 +117,7 @@ public String getAddCommand() {
         return sb.toString();
     }
 
-	// @@author A0092390E
+	// @@author A0092390E-repeated
     @Override
     public boolean is(String query) {
         query = query.toLowerCase();
```
Comment (darrenwee) [inline src/test/java/seedu/sudowudo/testutil/TestItem.java]: REASSIGNING METHOD PARAMETERS?! Mother Codacy will be cross >:-( 💢

**Review by darrenwee — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/sudowudo/model/item/Item.java (hunk 3 above)
Comment (darrenwee) [reply src/main/java/seedu/sudowudo/model/item/Item.java:254]: i am stupid ignore this

File: src/test/java/seedu/sudowudo/logic/LogicManagerTest.java (hunk 7 above)
Comment (craaaa) [reply src/test/java/seedu/sudowudo/logic/LogicManagerTest.java]: fixed

File: src/test/java/seedu/sudowudo/testutil/ItemBuilder.java (hunk 9 above)
Comment (craaaa) [reply src/test/java/seedu/sudowudo/testutil/ItemBuilder.java:27]: fixed

File: src/test/java/seedu/sudowudo/testutil/ItemBuilder.java (hunk 8 above)
Comment (craaaa) [reply src/test/java/seedu/sudowudo/testutil/ItemBuilder.java:32]: fixed

File: src/test/java/seedu/sudowudo/testutil/TestItem.java (hunk 10 above)
Comment (craaaa) [reply src/test/java/seedu/sudowudo/testutil/TestItem.java]: FIXED

File: src/test/java/seedu/sudowudo/logic/LogicManagerTest.java (hunk 6 above)
Comment (craaaa) [reply src/test/java/seedu/sudowudo/logic/LogicManagerTest.java]: fixdd

File: src/main/java/seedu/sudowudo/logic/commands/EditCommand.java (hunk 1 above)
Comment (craaaa) [reply src/main/java/seedu/sudowudo/logic/commands/EditCommand.java:92]: DONE

**Comment by craaaa** [comment]
Changes have been made
& they broke some things.
So I fixed those things too
This comment is a square!
Not yet, but perhaps now?
Not yet, but perhaps now?

**Review by darrenwee — APPROVED** [review]

**Comment by darrenwee** [comment]
LOOKS GOOD TO ME
